theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jemoji
  
# Build settings
markdown: kramdown

permalink: pretty

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
